version: '3.5'

services:
  velvetech-webapi:
    image: maiznpetr/velvetech-task:latest
    volumes:
      - /docker-data/velvetech/logs/webapi/:/app/logs
    environment:
      - ConnectionStrings:Student=Server=${SQL_URL:-velvetech-mariadb};Port=3306;Database=student;User ID=${SQL_USER:-root};Password=${SQL_ROOT_USER_PASSWORD:-123456};
      - ConnectionStrings:StudentMigration=Server=${SQL_URL:-velvetech-mariadb};Port=3306;Database=student;User ID=${SQL_USER:-root};Password=${SQL_ROOT_USER_PASSWORD:-123456};
    depends_on:
      - velvetech-mariadb
    restart: always

#  velvetech-client:
#    image: maiznpetr/velvetech-client:latest
#    depends_on:
#      - velvetech-proxy
#    restart: always

  velvetech-proxy:
    image: nginx:1.15.10-alpine
    ports:
      - "80:80"
    volumes:
      - /docker-data/velvetech/logs/proxy/:/var/log/nginx 
      - ./nginx/velvetech.conf:/etc/nginx/conf.d/default.conf    
      - ./nginx/velvetech-upstreams/api.conf:/etc/nginx/conf.d/velvetech-upstreams/api.conf
      - ./nginx/velvetech-locations/api.conf:/etc/nginx/conf.d/velvetech-locations/api.conf
    depends_on:
      - velvetech-webapi
    restart: always

  velvetech-mariadb:
    image: mariadb:10.3.22
#    ports:
#       - "3306:3306"
    volumes:
      - /velvetech-data/velvetech/mariadb:/var/lib/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_USER_PASSWORD:-123456}
      - MYSQL_USER=${SQL_USER:-root}
      - MYSQL_PASSWORD=${SQL_PASSWORD:-123456}
    restart: always

volumes:
  velvetech-data:
    driver: local
