export enum StudentActionsType {
    PROC_GET_LIST = 'PROC_GET_STUDENTS',
    SUCC_GET_LIST = 'SUCC_GET_STUDENTS',
    FAILED_GET_LIST = 'FAILED_GET_STUDENTS',

    SUCC_ADD = "SUCC_ADD_STUDENT",
    PROC_ADD = "PROC_ADD_STUDENT",
    FAILED_ADD = "FAILED_ADD_STUDENT",

    PROC_DELETE = "PROC_DELETE_STUDENT",
    SUCC_DELETE = "SUCC_DELETE_STUDENT",
    FAILED_DELETE = "FAILED_DELETE_STUDENT",

    PROC_UPDATE = "PROC_UPDATE_STUDENT",
    SUCC_UPDATE = "SUCC_UPDATE_STUDENT",
    FAILED_UPDATE = "FAILED_UPDATE_STUDENT"
}